# Generated by Django 4.2.10 on 2024-04-16 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EventTitle", models.CharField(max_length=100)),
                ("Event_Date", models.DateField()),
                ("Description", models.TextField()),
                ("Address", models.TextField()),
                ("Contact_Number", models.CharField(max_length=15)),
            ],
        ),
    ]
