# Generated by Django 4.2.10 on 2024-04-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_events"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Students",
        ),
    ]
