# Generated by Django 4.2.10 on 2024-04-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_delete_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="qr_code",
            field=models.ImageField(blank=True, upload_to="qr_codes"),
        ),
    ]
