# Generated by Django 4.2.10 on 2024-04-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_events_qr_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="events",
            name="qr_code",
        ),
    ]
