# Generated by Django 5.0.4 on 2024-05-29 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
