# Generated by Django 4.2.10 on 2024-04-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_events_qr_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("GuestName", models.CharField(max_length=100)),
                ("Email", models.EmailField(max_length=254)),
                ("Address", models.TextField()),
                ("Contact_Number", models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name="events",
            name="EventTitle",
            field=models.CharField(max_length=255),
        ),
    ]
